language: java
# from here: https://guides.gradle.org/executing-gradle-builds-on-travisci/
script:
- ./gradlew spotlessCheck test -s
notifications:
  email: false
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
